# We are using parallel jobs here
version: 2
orbs:
  saucectl: friggahel/saucectl@dev:alpha
jobs:
  saucectl:
    working_directory: ~/repo/testrunner-toolkit/cypress
    docker:
      - image: circleci/node:dubnium  # primary container for the build job
    steps:
      - checkout
      - saucectl/run

workflows:
  version: 2
  build:
    jobs:
      - saucectl
