# We are using parallel jobs here
version: 2
orbs:
  saucectl: friggahel/saucectl@dev:alpha
jobs:
  saucectl:
    working_directory: ~/repo/testrunner-toolkit/cypress
    docker:
      - image: circleci/node:dubnium  # primary container for the build job
    steps:
      - checkout
      - saucectl/run
  # WebdriverIO headless and best practices
  webdriverio:
    working_directory: ~/repo
    docker:
      - image: circleci/node:dubnium  # primary container for the build job
    steps:
      - checkout
      - run:
          name: "Update NPM"
          command: |
            sudo npm install -g npm@latest
      - run:
          name: "Run WebdriverIO Headless"
          command: |
            cd webdriverio/webdriver/examples/headless
            npm install
            npm run test.saucelabs.headless
      - run:
          name: "Run WebdriverIO Best Practices"
          command: |
            cd webdriverio/webdriver/best-practices
            npm install
            npm run test.saucelabs.us -- --maxInstances=25


workflows:
  version: 2
  build:
    jobs:
      - notRecommended
      - testcafe
      - webdriverio
