# We are using parallel jobs here
version: 2.1
orbs:
  saucectl: friggahel/saucectl@dev:alpha
jobs:
  saucectl:
    working_directory: ~/testrunner-toolkit/cypress
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - saucectl/saucectl-run

workflows:
  build:
    jobs:
      - saucectl
#####