# We are using parallel jobs here
version: 2.1
orbs:
  saucectl: friggahel/saucectl@dev:alpha
jobs:
  saucectl-local:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - saucectl/saucectl-run:
          working-directory: testrunner-toolkit/cypress
  saucectl-sauce:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - saucectl/saucectl-run:
          working-directory: testrunner-toolkit/cypress
          testing-environment: sauce
          suite: Cypress Chrome

workflows:
  build:
    jobs:
      - saucectl-local
      - saucectl-sauce
#########