# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Test

on:
  push:
    branches: ['*']

env:
  CLOUDSDK_PYTHON: python3.7
  SAUCECTL_VERSION: "0.24.2"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: ./.github/actions/saucectl-action
        with:
          version: v0.24.2
          run:
            working-directory: ./testrunner-toolkit/cypress/
            skip: true
